// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHLK06vrmSv37TgxV49aqYRWUTJ2ALk-c',
    appId: '1:847228825019:web:cbe3d9320c3ca1a44c689e',
    messagingSenderId: '847228825019',
    projectId: 'rating-system-24f88',
    authDomain: 'rating-system-24f88.firebaseapp.com',
    databaseURL: "https://rating-system-24f88-default-rtdb.firebaseio.com/",
    storageBucket: 'rating-system-24f88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQIMZHAgIP9arxZpP2INdOPXBxHZLyEzA',
    appId: '1:847228825019:android:9aea7291a25591ee4c689e',
    messagingSenderId: '847228825019',
    projectId: 'rating-system-24f88',
    storageBucket: 'rating-system-24f88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIkSfnD7SHVSF1xQBftw4Edwnu-DYL-fY',
    appId: '1:847228825019:ios:2bea3b58eaf8dea14c689e',
    messagingSenderId: '847228825019',
    projectId: 'rating-system-24f88',
    storageBucket: 'rating-system-24f88.appspot.com',
    iosBundleId: 'com.example.ratingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIkSfnD7SHVSF1xQBftw4Edwnu-DYL-fY',
    appId: '1:847228825019:ios:e8a14b1e3ac6aa514c689e',
    messagingSenderId: '847228825019',
    projectId: 'rating-system-24f88',
    storageBucket: 'rating-system-24f88.appspot.com',
    iosBundleId: 'com.example.ratingSystem.RunnerTests',
  );
}
